version: "3.9"

services:
  nexus:
    image: sonatype/nexus:latest
    container_name: nexusoss
    restart: always
    mem_limit: 4096m
    cpus: 4
    ports:
      - "0.0.0.0:8081-8181:8081-8181"
    environment:
      INSTALL4J_ADD_VM_PARAMS: "-Xms1g -Xmx4g -XX:MaxDirectMemorySize=2g -Djava.util.prefs.userRoot=/nexus-data/javaprefs"
    volumes:
      - ./nexus-data:/nexus-data
